### ISSUE TITLE
BP authenticity in contract execution.

### ISSUE THREAD

**Issue by shiwk** [AElfProject/AElf#1000]
I want to know whether we can check transaction sender is current block producer in contract. And for clear below is the case :

For system transactions, like cross chain indexing transaction, I only want producer of current block to do this indexing. In some bad cases, other BPs can also send the "bad" transaction (maybe they want more indexing fee) to the current BP which is not noticed. If BP authenticity cannot be checked in contract, the "bad" one is going to be executed successfully.

Of course it is possible to arrange order to let some valid transactions first and make followings failed, but it depends on the order overmuch. What's more, validation for the indexing is also needed after execution considering the order. So I don't think fixed transaction order is a good solution.

For me, the easiest way is **Address** of current producer is available in contract.

**Comment by shiwk** [comment]
How do you think? @loning

**Comment by loning** [comment]
sdk can provide Miner

**Comment by aerkol** [comment]
DPoS contract also have this issue, there are methods in DPoS contract that should be called only by block producers.

**Comment by shiwk** [comment]
> DPoS contract also have this issue, there are methods in DPoS contract that should be called only by block producers.

I agree. It is not protected yet?

**Comment by aerkol** [comment]
> I agree. It is not protected yet?

Not that I am aware of...

**Comment by aerkol** [comment]
#797 second item is also related to this issue.
