### ISSUE TITLE
Two things about signature.

### ISSUE THREAD

**Issue by shiwk** [AElfProject/AElf#1034]
1. (**TBD**) The hash of block/transaction doesn't involve signature data. 

2. The block hash is calculated from header data, but nothing at all about block body.  I think It is not safe enough and should be changed. See [this](https://github.com/AElfProject/AElf/blob/dev/AElf.Kernel.Types/Block/Block.cs#L40-L43).

**Comment by loning** [comment]
2. header has tx merkle tree root, enough @shiwk

**Comment by shiwk** [comment]
Right, this can be closed.
