### ISSUE TITLE
Transaction generation interface.

### ISSUE THREAD

**Issue by shiwk** [AElfProject/AElf#1063]
For this system txn generation [interface](https://github.com/AElfProject/AElf/blob/dev/AElf.Kernel.Core/Miner/Application/ISystemTransactionGenerator.cs#L8-L9), only previous block hash **prefix** is available but not real block hash. It can be changed to whole hash data? Because I'm using readonly txn to read state which needs the previous block hash as chain context. 

BTW, **Consensus** module uses **IBlockChainService** to get current information about the **chain** to make it work now.

**Comment by shiwk** [comment]
@loning How do you think?

**Comment by loning** [comment]
ok

发自我的 iPhone

**Comment by shiwk** [comment]
Check this [PR](https://github.com/AElfProject/AElf/pull/1064).
