### ISSUE TITLE
Rpc - GetTransactionResult only return TransactionId message

### ISSUE THREAD

**Issue by EricBlack** [AElfProject/AElf#1083]
Generate one transaction but not broadcast and execute, query with transactionId got result only contain TransactionId message.
![image](https://user-images.githubusercontent.com/5166529/53869497-53814000-4033-11e9-9cbb-e51a6bb00e6b.png)

Debug GetTransaction method we found issue caused by TransactionResult ToString() method.
![image](https://user-images.githubusercontent.com/5166529/53869665-9d6a2600-4033-11e9-9229-2324d3704946.png)

**Comment by rosona** [comment]
Fixed.
