### ISSUE TITLE
security/smart contract context

### ISSUE THREAD

**Issue by loning** [AElfProject/AElf#1090]
can we just put the security safe function in IContext?

for security, we make the assembly can not use reflection to get the object IInternalContext:IContext.
can we just make the sdk can get IContext? because we may have different SDKs, the SDK is more like a Client, in my opinion, we should not trust any Client.

**Comment by loning** [comment]
@gldeng

**Comment by gldeng** [comment]
During the runtime, the whole sdk assembly is injected by the node instead of provided by user, so I think there is no much difference if we put the sensitive code in sdk or in another library.

**Comment by loning** [comment]
but we need to check in js sdk，java sdk

发自我的 iPhone

**Comment by loning** [comment]
fixed https://github.com/AElfProject/AElf/pull/1118
