### ISSUE TITLE
Rpc 'Call' method execution got exception

### ISSUE THREAD

**Issue by EricBlack** [AElfProject/AElf#1105]
## Description
Project: AElf.OS.Rpc.ChainController.Tests/ChainControllerRpcServiceTest.cs

Run 'Call_ReadOnly_Success' test case got transaction execution error, and after debug we found trace error, details in below:
{ "TransactionId": "3e2fafbb02aa85590011816a3ead0557e2b0e3f77033529c69389ab763195024", "StdErr": "\nSystem.Reflection.TargetParameterCountException: Parameter count mismatch.\n   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\n   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\n   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)\n   at AElf.Runtime.CSharp.Core.MethodHandler`1.Execute(Byte[] paramsBytes) in /Users/chaipan/GitHub/AElf/AElf.Runtime.CSharp.Core/MethodHandler`.cs:line 34\n   at AElf.Runtime.CSharp.Executive.ExecuteMainTransaction() in /Users/chaipan/GitHub/AElf/AElf.Runtime.CSharp/Executive.cs:line 135", "InlineTransactions": [ { "From": "6LsvxLuXEYEeoD2R6EwEBFEMWViQWcUWdc38HhwdjBEksmT", "To": "3AhZRe8RvTiZUBdcqCsv37K46bMU2L2hH81JF8jKAnAUup9", "MethodName": "ChargeTransactionFees", "Params": "CAA=" } ], "Elapsed": "3247050", "ExecutionStatus": "ContractError", "StateSet": { } }

**Comment by gldeng** [comment]
The issue will be solved in #1025

**Comment by EricBlack** [comment]
Close the issue due to fixed. And skipped case have been recovered.
