### ISSUE TITLE
AElf.Runtime.CSharp3.Tests.TestContract cannot be compiled

### ISSUE THREAD

**Issue by sxq613** [AElfProject/AElf#1272]
protoc command report error:
  --contract_out: protoc-gen-contract: Plugin failed with status code 3221225781.

OS: Windows

**Comment by sxq613** [comment]
<Exec Condition="$([MSBuild]::IsOsPlatform(Windows))" Command="protoc --proto_path=../protobuf --csharp_out=./Protobuf/Generated --csharp_opt=file_extension=.g.cs --contract_out=./Protobuf/Generated test_contract.proto --plugin=protoc-gen-contract=../scripts/contract_csharp_plugin.exe" />

**Comment by rosona** [comment]
> contract_out

Looks likely that this is caused by missing Visual C++ Redistributable, can you install and try agin?
