### ISSUE TITLE
Fix unit tests related to transaction execution

### ISSUE THREAD

**Issue by gldeng** [AElfProject/AElf#135]

**Comment by gldeng** [comment]
The following tests need to be fixed:

- [ ] ChainTest.cs
- [ ] BlockTest.cs
- [ ] Miner\MinerLifetime.cs

**Comment by Justbeingjustin** [comment]
@gldeng what are your thoughts on the fix for ChainTest.cs? Let me know if you think I left something out.

**Comment by gldeng** [comment]
@Justbeingjustin  I'm leaving these remaining fixes to @shiwk  as he is the one who created them.
