### ISSUE TITLE
Remove VerifySignatureAsync in IAccountService

### ISSUE THREAD

**Issue by gldeng** [AElfProject/AElf#1382]
Method `VerifySignatureAsync` doesn't belong to IAccountService. It doesn't use any of the fields in the class and it is only used in tests.

https://github.com/AElfProject/AElf/blob/cb72c01f21f696bcf4c9fb61036d930688a46c6b/AElf.Kernel.Core/Account/Application/IAccountService.cs#L9

**Comment by rosona** [comment]
Fixed
