### ISSUE TITLE
Basic Voting Contract

### ISSUE THREAD

**Issue by EanCuznaivy** [AElfProject/AElf#1505]
Demands:

- [x] Register a voting topic and its acceptable token symbol, due time, etc.
This symbol must be created with white list contains Basic Voting Contract, otherwise this contract can't lock voters' tokens.

- [x] Vote for this topic.
Use `Lock` method in MultiToken Contract.

- [x] Query result of a certain voting topic.

- [x] Withdraw votes.
Use `Unlock` method in MultiToken Contract.

**Comment by rosona** [comment]
Finished
