### ISSUE TITLE
Cancelled Transactions should not be included in block

### ISSUE THREAD

**Issue by gldeng** [AElfProject/AElf#1533]
https://github.com/AElfProject/AElf/blob/bc6829445d72e0e2063e18bfa1a1fc67dabe4380/test/AElf.Kernel.SmartContractExecution.Tests/Application/BlockExecutingServiceTests.cs#L57

Here the test checks the cancelled transactions are in the block. However, the original logics are wrong. Cancelled transactions should not be treated as failed and shouldn't be packed into the block.

Both the actual logics and test need to be fixed.

**Comment by rosona** [comment]
Fixed.
