### ISSUE TITLE
Change double/float to decimal for calculation in contracts

### ISSUE THREAD

**Issue by gldeng** [AElfProject/AElf#1558]
https://github.com/AElfProject/AElf/blob/f20e45f3bdd88d14e17466d39f28bd5de1b795b5/src/AElf.Consensus.DPoS.Types/VotingRecord.cs#L10

`double` and `float` are hardware dependent and should not be used in contracts, use `decimal` instead. Check #727

**Comment by rosona** [comment]
Fixed
