### ISSUE TITLE
Contract security handle about when got unexpected bug

### ISSUE THREAD

**Issue by EricBlack** [AElfProject/AElf#1594]
## Description
What if you just got it wrong, published the contract, and it's out in the wild, people are using it, and something bad has happened?

Should there be a 'pause' option for the owner, or some other set of stakeholders? What should happen to money if there's an unexpected bug that leaves the contract underfunded? What general categories of states could a bug leave us in, and how should each of those be dealt with or remediated?
And how do you want to handle that? Who should have the right to pause it? Should there be time limits on the pausing? Should there be a limit as to how often the code can be paused?

**Comment by rosona** [comment]
1. The developer's resource token will be charged when executes the transaction. If the resource token is gone, it cannot be executed
2. Users can upgrade the contract to fix the problem
