### ISSUE TITLE
[discuss]About BasicContractZero

### ISSUE THREAD

**Issue by hzz780** [AElfProject/AElf#1656]
When we call DeploySmartContract, we don't have to input the name of the contract.
Then, we can not  call getAddessByName to get the address of the contract.

Can we input the name when we call DeploySmartContract?

**Comment by loning** [comment]
api should not call DeploySystemSmartContract, call DeploySmartContract

**Comment by loning** [comment]
@hzz780

**Comment by hzz780** [comment]
DeploySmartContract will not set the Name:Address in db. It is a feature.
