### ISSUE TITLE
Can't build successfully due to build commands for protobuf

### ISSUE THREAD

**Issue by thedonmon** [AElfProject/AElf#1723]
Trying to spin up a local node but cant get the Launcher to run due to a bunch of commands failing on Windows 10. Looks like its related to the build events that call commands to run bat scripts for running the protobufs. Also windows doesnt recognize some unzip commands as well. What am I missing here?

**Comment by rosona** [comment]
Install unzip on windows in the following: 
https://chocolatey.org/packages/unzip

**Comment by rosona** [comment]
> Trying to spin up a local node but cant get the Launcher to run due to a bunch of commands failing on Windows 10. Looks like its related to the build events that call commands to run bat scripts for running the protobufs. Also windows doesnt recognize some unzip commands as well. What am I missing here?

The easiest way to install unzip on windows in the following:
https://chocolatey.org/packages/unzip

**Comment by LyonNee** [comment]
You may have the same problem as me.Missing unzip and protoc environments.
This is the link to download unzip: [](https://sourceforge.net/projects/gnuwin32/files/unzip/5.51-1/unzip-5.51-1.exe/download?use_mirror=nchc&download=)

This is a solution about: [](protoc:https://blog.csdn.net/liupeifeng3514/article/details/78985575)

**Comment by loning** [comment]
we should put install shell command in readme and tutorial

发自我的 iPhone
