### ISSUE TITLE
Unnessary multiple-time loading of smart contract zero

### ISSUE THREAD

**Issue by gldeng** [AElfProject/AElf#1726]
## Description:

Tests for contracts takes very long time (a few minutes).

## Cause:
A node is started when running every contracts. And when starting the node, method `BlockchainNodeContextService.StartAsync` has the following logics which requires invoking view only method of contract zero:
https://github.com/AElfProject/AElf/blob/c71aeb130525024650c4ba264bae40423c24230f/src/AElf.Kernel.Node/Application/IBlockchainNodeContextService.cs#L65-L66

However, in `SmartContractExecutiveService` cache is not stored for contract zero, and in `PutExecutive` the executive cannot be put to cache pool. So the contract zero code is being loaded multiple times for every test.

https://github.com/AElfProject/AElf/blob/c71aeb130525024650c4ba264bae40423c24230f/src/AElf.Kernel.SmartContract/Application/ISmartContractExecutiveService.cs#L59-L83

https://github.com/AElfProject/AElf/blob/6ea514bfc6d7b3fffc45083ddc025387c1f4b40f/src/AElf.Kernel.SmartContract/Application/ISmartContractExecutiveService.cs#L103-L117

## Workaround:
Blindly put back all executive in DEBUG mode.

```csharp
        public async Task PutExecutiveAsync(Address address, IExecutive executive)
        {
            if (_executivePools.TryGetValue(address, out var pool))
            {
#if DEBUG
                pool.Add(executive);    
#else
                if (_addressSmartContractRegistrationMappingCache.TryGetValue(address, out var reg))
                {
                    if (reg.CodeHash == executive.ContractHash)
                    {
                        pool.Add(executive);
                    }
                }
#endif

            }

            await Task.CompletedTask;
        }
```

**Comment by gldeng** [comment]
@rosona can you assign an owner for this issue?

**Comment by loning** [comment]
fixed
