### ISSUE TITLE
Parallel execution is failing with NullReferenceException

### ISSUE THREAD

**Issue by aerkol** [AElfProject/AElf#1764]
When stress testing the node, after certain number of mining, the node fails executing with below error:

> 2019-06-01 02:00:33,904 [24] WARN  AElf.TaskQueue - Object reference not set to an instance of an object.
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at AElf.Kernel.TransactionTrace.GetFlattenedReads()+MoveNext() in /home/aelf/github/AElf/src/AElf.Kernel.Types/Transaction/TransactionTrace.cs:line 69
>    at AElf.Kernel.SmartContract.Application.TransactionExecutingService.GetReturnSet(TransactionTrace trace, TransactionResult result) in /home/aelf/github/AElf/src/AElf.Kernel.SmartContract/Application/ITransactionExecutingService.cs:line 275
>    at AElf.Kernel.SmartContract.Application.TransactionExecutingService.ExecuteAsync(TransactionExecutingDto transactionExecutingDto, CancellationToken cancellationToken, Boolean throwException, BlockStateSet partialBlockStateSet) in /home/aelf/github/AElf/src/AElf.Kernel.SmartContract/Application/ITransactionExecutingService.cs:line 90
>    at AElf.Kernel.SmartContract.Parallel.LocalParallelTransactionExecutingService.ExecuteAsync(TransactionExecutingDto transactionExecutingDto, CancellationToken cancellationToken, Boolean throwException, BlockStateSet partialBlockStateSet) in /home/aelf/github/AElf/src/AElf.Kernel.SmartContract.Parallel/LocalParallelTransactionExecutingService.cs:line 56
>    at AElf.Kernel.SmartContract.Parallel.LocalParallelTransactionExecutingService.ExecuteAsync(TransactionExecutingDto transactionExecutingDto, CancellationToken cancellationToken, Boolean throwException, BlockStateSet partialBlockStateSet) in /home/aelf/github/AElf/src/AElf.Kernel.SmartContract.Parallel/LocalParallelTransactionExecutingService.cs:line 56
>    at AElf.Kernel.SmartContractExecution.Application.BlockExecutingService.ExecuteBlockAsync(BlockHeader blockHeader, IEnumerable`1 nonCancellableTransactions, IEnumerable`1 cancellableTransactions, CancellationToken cancellationToken) in /home/aelf/github/AElf/src/AElf.Kernel.SmartContractExecution/Application/BlockExecutingService.cs:line 59
>    at AElf.Kernel.Miner.Application.MiningService.MineAsync(RequestMiningDto requestMiningDto, List`1 transactions, Timestamp blockTime) in /home/aelf/github/AElf/src/AElf.Kernel/Miner/Application/MinerService.cs:line 161
>    at AElf.Kernel.Miner.Application.MinerService.MineAsync(Hash previousBlockHash, Int64 previousBlockHeight, Timestamp dateTime, Duration blockExecutionTime) in /home/aelf/github/AElf/src/AElf.Kernel/Miner/Application/MinerService.cs:line 66
>    at AElf.Kernel.ConsensusRequestMiningEventHandler.<>c__DisplayClass9_0.<<HandleEventAsync>b__0>d.MoveNext() in /home/aelf/github/AElf/src/AElf.Kernel/ConsensusRequestMiningEventHandler.cs:line 52
> --- End of stack trace from previous location where exception was thrown ---
>    at AElf.TaskQueue.StartAsync() in /home/aelf/github/AElf/src/AElf.Core/ITaskQueue.cs:line 69

**Comment by rosona** [comment]
Fixed.
