### ISSUE TITLE
Refactor BlockChainAppService.BlockChainAppService(IBlockchainService, ISmartContractAddressService, ITransactionReadOnlyExecutionService, ITransactionManager, ITransactionResultQueryService, IBlockExtraDataService, ITxHub, IBlockchainStateManager, ITaskQueueManag

### ISSUE THREAD

**Issue by loning** [AElfProject/AElf#1789]
I've selected [**BlockChainAppService.BlockChainAppService(IBlockchainService, ISmartContractAddressService, ITransactionReadOnlyExecutionService, ITransactionManager, ITransactionResultQueryService, IBlockExtraDataService, ITxHub, IBlockchainStateManager, ITaskQueueManag**](https://github.com/AElfProject/AElf/blob/6592146786367af98859d3f564b46cb626f55060/src/AElf.WebApp.Application.Chain/BlockChainAppService.cs#L76-L99) for refactoring, which is a unit of **13** lines of code and **9** parameters. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Keep Unit Interfaces Small** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the number of parameters per unit to at most 4.
- **Why**❓ 
Keeping the number of parameters low makes units easier to understand, test and reuse.
- **How** 🔧 
Reduce the number of parameters by grouping related parameters into objects. Alternatively, try extracting parts of units that require fewer parameters.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by loning** [comment]
split them into different AppServices

**Comment by rosona** [comment]
Fixed.
