### ISSUE TITLE
Increase miners count to 17 after the replacement of initial miners

### ISSUE THREAD

**Issue by EanCuznaivy** [AElfProject/AElf#1801]
Currently the miners count abide to the count of initial miners and not changeable in the future.

According to our white paper, at the beginning of out main chain, miners count should be 17 and increase 2 each year. Since all the initial miners (nodes to launch main chain) maintained by the core team, maybe 5 nodes will be enough to complete the token initialization and other necessary task.

Thus the feature will be like this:
For (at least) first term, miners count abide to config files and the number doesn't matter. **The replacement of initial miners can only happens after the count of valid candidates greater than or equal to 17.**

**Comment by YanhuaViolet** [comment]
Have done it.Change the initialNumber to 17 at first round;
Then the miners' count will increase 2 when the term changed

**Comment by rosona** [comment]
finished.
