### ISSUE TITLE
[Developer community][Demo]中文社区：如何解决issue和提pr

### ISSUE THREAD

**Issue by hzz780** [AElfProject/AElf#1846]
需求描述：

1. 我们要找到yiqi。
2. 按照教程跑通  https://github.com/AElfProject/aelf-boilerplate/tree/hello-world
3. 跑通后和yiqi一天喝八杯可乐。
4. 成为yiqi的朋友。

奖励：

奖励 58.88个 ELF 【不同的issue的奖励不一样，最后以和团队确认为准】

**Comment by hzz780** [comment]
基础步骤
- 从开放给社区的issue中，领取认为自己可以解决的issue（给出奖励范围）
- 明确需求，提交解决方案，并获取认可
- 创建PR并添加[WIP][community]
- 细分任务，标注任务完成期限
- 完成PR后，添加标签“review”
- 看到“review”标签的PR，开始Team review
- 通过Team reivew后，移除标题中的[WIP][community]，等待最终review

**Comment by atom-yang** [comment]
1. 去开发者社区的QQ群能找到yiqi。
2. 诶特yiqi喝可乐。
3. 在群里活跃，解决大家提出的技术问题，发现AELF的bug，优化AELF的工程，就能成为yiqi的朋友了。

我想要 100~200个ELF

**Comment by hzz780** [comment]
1. 方案靠谱。
2. 去提pr吧。
3. 预算ok，根据实际完成情况发放。

祝你编码愉快。

**Comment by hzz780** [comment]
# 进阶

通过 better code hub 自助提issue
链接： https://bettercodehub.com

步骤：
1. fork AELF项目
2. 通过better code hub 分析

点击分析按钮
![在这里插入图片描述](https://img-blog.csdnimg.cn/20190626202233598.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L2h6ejc4MA==,size_16,color_FFFFFF,t_70)

查看结果，并选择对应问题，根据提示提issue即可。
![image](https://user-images.githubusercontent.com/7567714/60179480-54431980-9850-11e9-8b2f-ee4cfe3b5a8a.png)

3.提完issue后，并提出解决方案和DDL，团队会给出奖励范围, 确认后即可。

**Comment by tomatopunk** [comment]
疑问:
只有项目的contributors才可以对pr or issues打标签...
按照流程..我(开发者) 开发完毕,为pr中添加review标签.
Reviewer code,去掉WIP,Merge到主分支..

这流程存在问题...

**Comment by hzz780** [comment]
@tomatopunk 
感谢，我们调整一下逻辑。🤔改成去掉[WIP], 新增[Community Review]

**Comment by tomatopunk** [comment]
> @tomatopunk
> 感谢，我们调整一下逻辑。🤔改成去掉[WIP], 新增[Review]

我接一个PR,来帮你们测试一下逻辑~~~

**Comment by JaneConan** [comment]
What does the process look like now? Which friend can reply, thank you 🙂
