### ISSUE TITLE
[Developer community]Refactor BlockchainNodeContextService.BlockchainNodeContextService(IBlockchainService, IChainCreationService, ITxHub, ISmartContractAddressUpdateService, IDefaultContractZeroCodeProvider, IConsensusService)

### ISSUE THREAD

**Issue by rosona** [AElfProject/AElf#1859]
I've selected [**BlockchainNodeContextService.BlockchainNodeContextService(IBlockchainService, IChainCreationService, ITxHub, ISmartContractAddressUpdateService, IDefaultContractZeroCodeProvider, IConsensusService)**](https://github.com/AElfProject/AElf/blob/35c1a91451217c5c2e7faf7793d09e650a97e063/src/AElf.Kernel.Node/Application/IBlockchainNodeContextService.cs#L41-L52) for refactoring, which is a unit of **8** lines of code and **6** parameters. Addressing this will make our codebase more maintainable and improve [Better Code Hub](https://bettercodehub.com)'s **Keep Unit Interfaces Small** guideline rating! 👍 

Here's the gist of this guideline:
- **Definition** 📖 
Limit the number of parameters per unit to at most 4.
- **Why**❓ 
Keeping the number of parameters low makes units easier to understand, test and reuse.
- **How** 🔧 
Reduce the number of parameters by grouping related parameters into objects. Alternatively, try extracting parts of units that require fewer parameters.

You can find more info about this guideline in [Building Maintainable Software](http://shop.oreilly.com/product/0636920049159.do). 📖 
 
---- 
ℹ️ To know how many _other_ refactoring candidates need addressing to get a guideline compliant, select some by clicking on the 🔲  next to them. The risk profile below the candidates signals (✅) when it's enough! 🏁 

----
Good luck and happy coding! :shipit: :sparkles: :100:

**Comment by tomatopunk** [comment]
Hi :
evening ~ I looked at the code ,want to make the following changes:

1.parameters by grouping,IBlockchainService ,IChainCreationService,ISmartContractAddressUpdateService ,IConsensusService 

2. Packaged into a BlockchainNodeContextProxyService

3. Inject BlockchainNodeContextProxyService in BlockchainNodeContextService 

Expected to be developed before 19/7/7 ~

**Comment by loning** [comment]
@tomatopunk ok，thx～
