### ISSUE TITLE
Cross chain transfer issues

### ISSUE THREAD

**Issue by gldeng** [AElfProject/AElf#1868]
## Code
https://github.com/AElfProject/AElf/blob/d557d12f85c21976526102f61906c00418f37958/contract/AElf.Contracts.MultiToken/TokenContract_Actions.cs#L111-L158

## Issues with `CrossChainReceiveToken`
1. It's not verified the original transaction is for the canonical `MultiToken` contract and its `CrossChainTransfer` method
1. The token is added to the `balanceOfReceiver` without issuing or transaferring (i.e. the sum of all balances won't tally the supply) and the change cannot be traced
1. There is no control of the source chain. As long as there is a txn happened on a side chain indexed by the main chain, it can cause the token on any other side chain to change. That means there's no limit of transfer if I just create a new chain and transfer my token to this chain.

**Comment by shiwk** [comment]
Close as code updated.
