### ISSUE TITLE
[Demand] NEW API:  get Contract Creation Code & Codehash

### ISSUE THREAD

**Issue by hzz780** [AElfProject/AElf#1874]
We need an API  to get 'Contract Creation Code'.

As we can update our contract. We also need an API to get the hash of the contract by address.

Example in etherscan:

https://etherscan.io/address/0x1b75b90e60070d37cfa9d87affd124bb345bf70a#contracts

They verify the contract manually.

https://etherscan.io/verifyContract

**Comment by rosona** [comment]
call genesis contract, GetSmartContractRegistrationByAddress, it's return 

message SmartContractRegistration {
    int32 category = 1;
    bytes code = 2;
    Hash code_hash = 3;
}

"code" is the contract code, "code_hash" is contract code hash.

**Comment by hzz780** [comment]
thx.
