### ISSUE TITLE
Implement block marking in transactions

### ISSUE THREAD

**Issue by gldeng** [AElfProject/AElf#188]
According to whitepaper's section 5.2.4 (v1.5 as of 27/02/2018), we need to mark block in transaction to ensure the validity of transactions.

After we implement this, nonce may not be required. And the batching for parallel execution is also not required. @shiwk @PadawanZH

**Comment by shiwk** [comment]
nonce represents the order of transactions from same address, used in transaction pool to wait old txs , maybe with same block mark. @gldeng

**Comment by gldeng** [comment]
Implemented in 440
