### ISSUE TITLE
Potential bottleneck with parallel processing

### ISSUE THREAD

**Issue by aerkol** [AElfProject/AElf#1890]
Noting an issue here although AElf Economic System PR (#1718) is still in progress.

- Currently charged resource tokens are accumulated like below when `ChargeResourceToken` in `MultiToken` contract is called:

```
State.Balances[Context.Self][pair.Key] = State.Balances[Context.Self][pair.Key].Add(pair.Value);
State.ChargedResources[pair.Key] = State.ChargedResources[pair.Key].Add(pair.Value);
```

Currently this will cause all transactions to be in the same group when grouping before parallel execution.

We should move the first line to `DonateResourceToken` method before calling `TreasuryContract.Donate`.
We should do the mapping of `State.ChargedResources` like we did in `ChargeTransactionFees`. Map as `ChargedResources[fromAddress][symbol]` instead of `ChargedResources[symbol]`.

- Another issue is that we reset `State.PreviousBlockTransactionFeeTokenSymbolList.Value` every time `ClaimTransactionFees` is called (at every new block to claim fees from previous block) so this state will be empty at each new block and later `ChargeTransactionFees` will need to add the charged fee symbol to this state when it is called. This will also cause conflict after parallel execution of transactions.

**Comment by EanCuznaivy** [comment]
Fixed in branch `feature/profits`
