### ISSUE TITLE
Merkle Hashing

### ISSUE THREAD

**Issue by samgranger** [AElfProject/AElf#19]
I see that you use MD5 for merkle hashing, why not SHA?

See: https://github.com/AElfProject/AElf/blob/ff73574afaf9ecf64f98ff472da4247c6586a209/AElf.Kernel/ExtensionMethods.cs

**Comment by xtaci** [comment]
it should be SHA-256.
@EanCuznaivy

**Comment by EanCuznaivy** [comment]
Thanks.
Already changed to SHA-256 yesterday in new PR.

**Comment by loning** [comment]
we should implement as interface，make it easy to change

**Comment by samgranger** [comment]
Wouldn't SHA-3 / Keccak be a better alternative?

**Comment by xtaci** [comment]
yes, sure , but interfaces are better

**Comment by samsoull** [comment]
Good

**Comment by mjostani2002** [comment]
Totally agree
