### ISSUE TITLE
About cross chain address validation.

### ISSUE THREAD

**Issue by shiwk** [AElfProject/AElf#1916]
# Description
In some cases that need cross chain verification, original contract address is needed to make sure the action is exactly as expected. 

# Scenario
Like #1885 , related to cross chain transfer from chain ***C<sub>1</sub>*** to chain ***C<sub>2</sub>***, actual token contract address of chain ***C<sub>1</sub>*** should be validated and stored on chan  ***C<sub>2</sub>***. 

# Solution

### Genesis Smart Contract

 `ValidateSystemContractAddress(address, hashName)` 
  
  Validate system contract address existence inside chain. 

### Contract SDK

`GetZeroSmartContractAddress(chainId)`
  
Return genesis contract address of specific chain.

### Step 1.  Validate itself locally

Transaction ***T***  on chain ***C<sub>1</sub>***  invoking 
`ValidateSystemContractAddress(address, hashName)`of genesis contract to validate token address  ***A*** existence.

### Step2. Validate address ***A*** on Chain ***C<sub>2</sub>*** 

Do cross chain verify  for transaction ***T***.  

If it succeeds,  token address  ***A*** from chain   ***C<sub>1</sub>*** can be trusted on chain ***C<sub>2</sub>***. 

What is more, in this processing, to be sure that transaction ***T*** exactly happened on right place,  genesis contract  address ***A<sub>0</sub>*** from chain ***C<sub>1</sub>*** can be checked by `GetZeroSmartContractAddress(chainId)` on Chain ***C<sub>2</sub>*** .

**Comment by aerkol** [comment]
This solves 1 and 3 in #1868 , however, we will need to take care of Guanglei's 2nd concern as well.

**Comment by shiwk** [comment]
> This solves 1 and 3 in #1868 , however, we will need to take care of Guanglei's 2nd concern as well.

Check #1885 . `TokenInfo` identity can be protected among chains.

**Comment by aerkol** [comment]
I understand, I thought this is mainly for cross chain transfer. I have no concern with this solution if it is purely to manage address validation in cross chain.

For cross chain transfer, I checked #1885 and I am still not clear how we will handle the token supply amount for a specific token. To transfer, we burn first (supply.sub(x)) then on the other chain we only add the amount on the balance of receiving address. Currently it is difficult to trace the number of tokens in circulation.

**Comment by shiwk** [comment]
> I understand, I thought this is mainly for cross chain transfer. I have no concern with this solution if it is purely to manage address validation in cross chain.
> 
> For cross chain transfer, I checked #1885 and I am still not clear how we will handle the token supply amount for a specific token. To transfer, we burn first (supply.sub(x)) then on the other chain we only add the amount on the balance of receiving address. Currently it is difficult to trace the number of tokens in circulation.

The code is not refactored yet. Receiver chain supply would be increased when cross chain received and total supply in `TokenInfo` won't be changed anytime.

**Comment by aerkol** [comment]
Got it, thank you.

**Comment by shiwk** [comment]
Close as code updated.
