### ISSUE TITLE
[Recommendation] Optimisation for maintaining beneficiaries in Election contract

### ISSUE THREAD

**Issue by aerkol** [AElfProject/AElf#1930]
Currently at each vote, the candidate is added / removed in profit contract. (`TryToBecomeAValidationDataCenter` is called in `Vote` method in `ElectionContract_Elector.cs`)

However, rewards are distributed to beneficiaries at each term, so beneficiaries don't need to be updated or maintained at each vote and it should be sufficient to do it at each term instead. So current implementation makes voting a bit heavy especially if 2 candidates are entering and exiting `DataCentersRankingList` at each vote.

**Comment by EanCuznaivy** [comment]
Hi, currently the `DataCentersRankingList` is used for getting next available miner when an evil miner detected, and also should be updated as soon as possible since our website shall show the ranking, so this list has updated during voting.

**Comment by aerkol** [comment]
I see, then it is a valid reason to do it at each vote, I am closing this issue...
