### ISSUE TITLE
[Recommendation] Removal of GenesisOwnerAddress from ParliamentAuth contract

### ISSUE THREAD

**Issue by aerkol** [AElfProject/AElf#1931]
Genesis contract's owner address is already stored in Genesis contract itself. Storing it in ParliamentAuth contract doesn't seem to provide any benefit (in term of call efficiency) and also causes duplicate information to be maintained in 2 separate contracts (although it is less likely to change after chain initialisation).

I recommend removing `GenesisOwnerAddress` from ParliamentAuth contract and get it directly from Genesis contract.

**Comment by shiwk** [comment]
Actually, what genesis contract stores is only an address. We use `GenesisOwnerAddress` as default for that address and it can be changed to another one after. This `GenesisOwnerAddress` is a calculated virtual address and it is also used by other contracts as virtual `From` address. I think it make sense if store this address where it was calculated.

**Comment by aerkol** [comment]
I understand, I think the name GenesisOwner may be misunderstood (like I did) as GenesisContract's owner and raise a question why we duplicate it in separate contracts.

I think this issue still can be left open as a low priority item to look later as I believe one of them should be changed to a better name.  When named same and initially set to a same address in initialisation, this may confuse external parties why they aren't remaining the same (one can be changed later while the other one cannot be changed) and one has to be an organisation address (BPs) but the other one doesn't although both are called the same name.

**Comment by aerkol** [comment]
Fixed in #2013 PR
