### ISSUE TITLE
Sender produced too many continuous blocks.

### ISSUE THREAD

**Issue by shiwk** [AElfProject/AElf#2099]
`Consensus validating before execution failed: Sender produced too many continuous blocks.`

With this warning, it is apparently known that miner generated more blocks than expected. The thing is it cannot be noticed before broadcast. As a result this invalid block would be broadcast to other peers as normal. 

While not too bad things happened, it is not good enough if cause all peers `Attach` and then `Switch` back. Is there any way to avoid this?

**Comment by shiwk** [comment]
Another thing worth mentioned is that some blocks would be generated with invalid timestamp and then broadcasted, as a result, causing all peers execution failed and switch again.

Expect:	 2019-12-12 16.45.14,330248
Actual:	
2019-12-12 16.45.16,370461
2019-12-12 16.45.16,893454
2019-12-12 16.45.17,415335
2019-12-12 16.45.17,850779
**2019-12-12 16.45.18,377720**

**Comment by rosona** [comment]
The first issue has been fixed, the second issue occurs occasionally in the case of a fork, and the second issue is improved together when improving the block acceptance rate.
