### ISSUE TITLE
Improvement to Prevent Contract Deployment / Update Timeout

### ISSUE THREAD

**Issue by aerkol** [AElfProject/AElf#2141]
**Background**
Before deployment / update of contracts, contract code should be checked for any disallowed libraries and also certain calls to standard libraries should be replaced with AElf SDK extensions.

Currently there are two operations that are time consuming and performed at the time of deployment / update transaction execution:

1. Contract check (ContractAuditor)
2. Contract patch (ContractPatcher)

Due to the time consuming nature of these procedures, currently most of the contract deployment and update transactions are failing (timing out) since it cannot be completed within block time (0.5 s).

**Solution Discussed**
Both operations (check, patch) will be moved outside of transaction execution.

When a call is made to `BasicContract` (Genesis Contract) to deploy / update a new contract code, `ContractInfo.CodeHash` won't point to the new code immediately. Instead, a deployment / update proposal will be created by `ProposeNewContract` in `BasicContract` to:

- check the contract code for disallowed libraries
- check that the contract code was patched correctly
- add the patched code to `SmartContractRegistration`
- update `CodeHash` in `ContractInfo` to the new patched code

(first 2 will be done by BPs outside of execution, last 2 will be done by the release of proposal)

The proposal will include both non-patched and patched versions of the contract code (initial patching will be done off-chain by AElf's CLI), so that BPs will be able to check by patching the non-patched version to verify that patched code can be trusted.

Besides creating a proposal, `BasicContract` will fire an event (`NewContractProposed`) that contains contract codes to trigger BPs to perform contract check and approve the proposal (proposal id will be retrieved from the transaction result that fires `NewContractProposed` event).

Once there are enough approvals for the new code, contract developer will need to make another call `ReleaseContract` in `BasicContract` that will make a call to release contract deployment / update proposal.

**Impact**
Below is to summarise the impact in the code, names are proposed and subject to change:
- Add a new method `ProposeNewContract` in `BasicContract`, this will be the one creating a deployment proposal with non-patched, patched code and also fire an event `NewContractProposed` containing the contract codes for validation, proposer will be `BasicContract.`
- Add a new method `ReleaseContract` in `BasicContract` to release the proposal that was proposed by `BasicContract`, releasing the proposal will make a call to our current `DeploySmartContract`. Developer will need to make a call to this method once contract code is approved by more than 2/3rd of the BPs.
- Block producers will need to monitor for `NewContractProposed` contract event in `BestChainFoundEventHandler`, to check the contract code and generate a transaction to approve the proposal.
- Similar approach should be followed for contract update.
- Test cases will need to be updated accordingly.

**Comment by shiwk** [comment]
> The proposal will include both non-patched and patched versions of the contract code (initial patching will be done off-chain by AElf's CLI), so that BPs will be able to check by patching the non-patched version to verify that patched code can be trusted.

Do you think whether it is possible if only patched code is provided?

**Comment by shiwk** [comment]
> Besides creating a proposal, BasicContract will fire an event (NewContractProposed) that contains the proposal id and contract codes to trigger BPs to perform contract check and approve the proposal.

Proposal id is not available when you create proposal with cross contract `send`. So proposal id should not be in this new event. But we already include proposal id in `ProposalCreated` event, and then it can be noticed. See #2135 .

**Comment by aerkol** [comment]
> > The proposal will include both non-patched and patched versions of the contract code (initial patching will be done off-chain by AElf's CLI), so that BPs will be able to check by patching the non-patched version to verify that patched code can be trusted.
> 
> Do you think whether it is possible if only patched code is provided?

We are considering add instruction meter to count the number of instructions executed to monitor CPU use per contract. In that case, it will be very tricky to check whether it is done correctly.

In current situation, the only amendment we make in contract is to replace some string operations with AElf SDK extensions. In this case, providing only patched code would help but if we go with the meter injection, then this will be a problem later.

**Comment by aerkol** [comment]
> > Besides creating a proposal, BasicContract will fire an event (NewContractProposed) that contains the proposal id and contract codes to trigger BPs to perform contract check and approve the proposal.
> 
> Proposal id is not available when you create proposal with cross contract `send`. So proposal id should not be in this new event. But we already include proposal id in `ProposalCreated` event, and then it can be noticed. See #2135 .

You are right, I amended the solution and removed including proposal id in event.
