### ISSUE TITLE
[Community Bug] SQL injection in wallet

### ISSUE THREAD

**Issue by satyasys** [AElfProject/AElf#2151]
**Describe the bug**
Add token is vulnerable to SQL injection

**To Reproduce**
1. Go to https://wallet-test.aelf.io/#/addtoken
2. Type elf'" or 1=1--
3. It says, Client Error
4. if you go to https://wallet-test.aelf.io/api/contract/searchtoken?name=elf%27%22+or+1%3D1--,
it says, {"message":"ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\" or 1=1--%'' at line 1"}

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS and version: [e.g. Ubuntu 18.04]
 - Dotnet core version [e.g. 2.2.106]

**Additional context**
![AelfSQLInjection](https://user-images.githubusercontent.com/48247373/68178783-2b404b80-ffdd-11e9-988a-06a1b485cf49.PNG)

**Comment by hzz780** [comment]
Cool.
Thanks.

**Comment by aelf-developer** [comment]
Dear satyasys,
Thank you for participating in aelf Enterprise 0.8.0 Beta version public testing.
We have received your issue and reviewed it. After the review, we decided to give you 888 ELF tokens as an award. Please contact aelf developer community staff for the award.

Contact Information:
QQ (Chinses): 1373175449 (Dayu)
WeChat (Chinses): a439714 (Dayu)
Telegram (English): @Samjia (Sam)

**Comment by satyasys** [comment]
Hello Aelf,

SQL injection is considered a P1 critical vulnerability and eligible for 1500 USD not 80 USD, kindly increase the reward.

**Comment by aelf-developer** [comment]
Thank you very much for your suggestion! For our Bug Bounty Program of aelf External Application, the highest reward is 888 ELF.
For details, please check it here: 
https://medium.com/aelfblockchain/aelf-launches-bug-bounty-c1e185f8aca4

We will host more developer events with great ELF token awards in aelf community, and you're welcome to join it again. Also, do you convenient to add our staff contact and communicate with us directly? 

Contact Information:
QQ (Chinses): 1373175449 (Dayu)
WeChat (Chinses): a439714 (Dayu)
Telegram (English): @Samjia (Sam)

**Comment by hzz780** [comment]
https://github.com/AElfProject/aelf-block-api/pull/19
