### ISSUE TITLE
Contracts should not use Object method 'GetHashCode'

### ISSUE THREAD

**Issue by EricBlack** [AElfProject/AElf#2281]
**Describe the bug**
The hash code of same object on different vm/machine are not the same, use hash code in contract may cause state data not consistency and caused block cannot pass verification issue. 
So contract code audit should be detected this scenario and not allow user use 'GetHashCode' in contract.

**Comment by aerkol** [comment]
I see that protobuf generated code is using a lot of GetHashCode.

I think one possible solution to this, is to use method call replacer which we already have, and replace calls to GetHashCode to our own implemented GetDeterministicHashCode in AElf.SDK.

I found a source that could be helpful for us in this context.

https://andrewlock.net/why-is-string-gethashcode-different-each-time-i-run-my-program-in-net-core/
