### ISSUE TITLE
Why `ScreenManager.AskInvisible` returns a `new NetworkCredential("", pwd).Password;`?

### ISSUE THREAD

**Issue by reyoung** [AElfProject/AElf#296]
The related code is here. I do not understand why here returns a `new NetworkCredential("", pwd).Password;` instead of just `pwd`.  

https://github.com/AElfProject/AElf/blob/e6a9e1a9cd39e20b121ec277f3f3ef01b1b7abb8/AElf.CLI/Screen/ScreenManager.cs#L287-L289

Is it because we want to use `SecureString`? Should we just return `SecureString` in the method `AskInvisible`?

**Comment by EricBlack** [comment]
Close due to fixed.
