### ISSUE TITLE
Cannot produce extra block due to need to wait 34000s

### ISSUE THREAD

**Issue by EricBlack** [AElfProject/AElf#320]
After a couple of time running on multi nodes, it will pop of a message: 
"[20:35:39 - DPoS]Will (help to) produce extra block after 34000s"

**Comment by EanCuznaivy** [comment]
When I change the MiningTime from 8000 to 4000, CheckTime from 2000 to 1000, the message is like this:
`[01:39:01 - Node]: Will (help to) produce extra block after 17000s `
This kind of message start nearly **at the same** for all 3 block producers.
I guess there's something wrong with the counting-down calculation.
Still trying to find the reason.

**Comment by EanCuznaivy** [comment]
No more such log or possible after latest refactoring of consensus part.
