### ISSUE TITLE
How to transfer the ELF instead of ELF token?

### ISSUE THREAD

**Issue by Wangmmx** [AElfProject/AElf#3297]
Hello, I am doing related wallet development work. I need to support AELF's mainnet currency transfer function. I have a few questions.
1. Can I test it on the testnet? Is there any transfer transaction for reference?
2. Is there a Nodejs demo about creating transfer transactions?
3. I see that the transaction receiver of Transfer type are all contract addresses. Is this the mainnet currency or token? Does the mainnet currency also need a contract? Is there a document for reference, thanks
Looking forward to your reply

**Comment by mason-hz** [comment]
> Hello, I am doing related wallet development work. I need to support AELF's mainnet currency transfer function. I have a few questions.
> 
> 1. Can I test it on the testnet? Is there any transfer transaction for reference?
> 2. Is there a Nodejs demo about creating transfer transactions?
> 3. I see that the transaction receiver of Transfer type are all contract addresses. Is this the mainnet currency or token? Does the mainnet currency also need a contract? Is there a document for reference, thanks
>    Looking forward to your reply

Hi, Wangmmx 
The following is a simple example
`tokenContract.Transfer({
    symbol: "ELF",
    to: "7s4XoUHfPuqoZAwnTV7pHWZAaivMiL8aZrDSnY9brE1woa8vz",
    amount: "1000000000",
    memo: "transfer in demo"
  });`
Nodejs detailed documentation can refer to [aelf-sdk.js](https://github.com/AElfProject/aelf-sdk.js)
I hope useful to you

**Comment by Wangmmx** [comment]
> > Hello, I am doing related wallet development work. I need to support AELF's mainnet currency transfer function. I have a few questions.
> > 
> > 1. Can I test it on the testnet? Is there any transfer transaction for reference?
> > 2. Is there a Nodejs demo about creating transfer transactions?
> > 3. I see that the transaction receiver of Transfer type are all contract addresses. Is this the mainnet currency or token? Does the mainnet currency also need a contract? Is there a document for reference, thanks
> >    Looking forward to your reply
> 
> Hi, Wangmmx
> 
> The following is a simple example:
> 
> ```
> tokenContract.Transfer({
>     symbol: "ELF",
>     to: "7s4XoUHfPuqoZAwnTV7pHWZAaivMiL8aZrDSnY9brE1woa8vz",
>     amount: "1000000000",
>     memo: "transfer in demo"
>   });
> ```
> 
> Nodejs detailed documentation can refer to [aelf-sdk.js](https://github.com/AElfProject/aelf-sdk.js).
> 
> I hope useful to you

Thanks for your reply
I have looked at the SDK and found that there are some methods in the contract class. This requires the contract address and wallet to initialize. Is there an offline method that can be used? I am taking apart these methods, but they seem to be more complicated, especially dataType, many of which are not available. 

What I want to do is  client-side signature, so I want 
1. Creating a transaction body completed offline,
2. To generate one Message to sign
3. Serialized into the final transaction body, I just broadcast it

**Comment by Wangmmx** [comment]
Solved myself
