### ISSUE TITLE
What is the mainnet public rpc node?

### ISSUE THREAD

**Issue by Wangmmx** [AElfProject/AElf#3305]
Looking for a long time and have not found yet
Thanks a lot!

**Comment by Wangmmx** [comment]
@mason-hz

**Comment by EanCuznaivy** [comment]
You can use 3.64.228.170 to launch a fullnode. This is one of the fullnodes of ours.
To be clear, config `appsettings.json`'s Network/BootNodes section:
```json
  "Network": {
    "BootNodes": ["3.64.228.170"],
    "ListeningPort": 6801
  },
```

**Comment by Wangmmx** [comment]
> You can use 3.64.228.170 to launch a fullnode. This is one of the fullnodes of ours.
> To be clear, config `appsettings.json`'s Network/BootNodes section:
> 
> ```json
>   "Network": {
>     "BootNodes": ["3.64.228.170"],
>     "ListeningPort": 6801
>   },
> ```

Thanks for your reply, but I can not connected to it, is it working now?

**Comment by Wangmmx** [comment]
I can use the testnet rpc: http://54.199.254.157:8000/

**Comment by hastings8** [comment]
i would love to learn how i can get started in running a full node any advice i could receive would be greatly appreciated

**Comment by EanCuznaivy** [comment]
> I can use the testnet rpc: http://54.199.254.157:8000/, but 3.64.228.170 is unavailable

Currently, we do not open the 8000 port to the public, these IP Addresses are just provided for syncing aelf MainNet MainChain data.

**Comment by EanCuznaivy** [comment]
> i would love to learn how i can get started in running a full node any advice i could receive would be greatly appreciated

Check docs.aelf.io :)

**Comment by Wangmmx** [comment]
> Currently, we do not open the 8000 port to the public, these IP Addresses are just provided for syncing aelf MainNet MainChain data.

OK, I built a node by myself, then I will use my own node to test. I want to confirm again, if I want to support ELF transfer transactions, do I only need to support the main chain AELF?
