### ISSUE TITLE
Will release a new version to switch back the Web API response json naming policy to upper camel case.

### ISSUE THREAD

**Issue by EanCuznaivy** [AElfProject/AElf#3320]
**Is your feature request related to a problem? Please describe.**
Yes. In origin `v1.2.0` version, the `UpperCamelCaseNamingStrategy` class of `AElf.WebApp.Web` doesn't take effect, and we release that version before a full test process is finished. So if anyone uses `v1.2.0` directly, all the aelf SDKs won't work normally.
That is a mistake.

**Describe the solution you'd like**
As there's already a fix in the `dev` branch (because we want a correct docker image quickly), I use a `UpperCamelCaseNamingPolicy` to replace the old `UpperCamelCaseNamingStrategy`, then the naming policy takes effect as in previous versions.
But maybe there's another solution which is more elegant. I'll try to figure it out.

**Describe alternatives you've considered**
It's a hotfix. Nothing more.

**Additional context**
Won't be so long.

TODO List:
- [x] Fork a `feature/v1.2.0-webapifix` branch from `master` branch (because we want to publish a new NuGet package for this fix)
- [x] Commit fix code to `feature/v1.2.0-webapifix`
- [x] PR `feature/v1.2.0-webapifix` to `dev` branch: #3321
- [x] Merge `feature/v1.2.0-webapifix`  to `dev` then `master`
- [x] Tag `v1.2.1`

**Comment by blocknodehub** [comment]
we have the same problem.

**Comment by EanCuznaivy** [comment]
> we have the same problem.

With aelf or .net?
