### ISSUE TITLE
[BUG]On test environment  Main chain and Side chain can't index block data  each other

### ISSUE THREAD

**Issue by YueZh127** [AElfProject/AElf#3595]
### Description
The main chain and side chain can’t index each other’s block data. The BP account doesn’t automatically send the `ProposeCrossChainIndexing` transaction to index the side/parent chain block data. After a period of time, an error `Validate block after execution failed: CrossChainValidationProvider` will be reported. and the node can't generate block.

### Environment
- Test Environment
- Node: v1.10.0

**Comment by chopin-fan** [comment]
The issue has been resolved. The cause was due to the parallel execution of the generation block and the generation system transaction, which has now been fixed.
