### ISSUE TITLE
Bug in WorldStateDictator.ApplyCachedDataAction

### ISSUE THREAD

**Issue by PadawanZH** [AElfProject/AElf#374]
The StateCache generated by a worker will be written to the database when this worker its current job. This is down by calling the function 
```
await _servicePack.WorldStateDictator.ApplyCachedDataAction(stateCache, chainContext.ChainId);
```
 in ``Worker.RunJob()``, which will convert the ResourcePath of the states in the cache to their corresponding pointer and use ``IDataStore.PipelineSetDataAsync()`` to store states into database.

- The problem happens in the step that converts the ResourcePath of the state to their corresponding pointer. Now we use **ResourcePath.PreviousBlockHash.CurrentBPAddress** to represent a pointer of the state when Get or Set the states in the database. However, ``ApplyCachedDataAction`` still uses the old **ResourcePath.PreviousBlockHash** as the pointer of the state. We will never find the data in the database because the key we used to set is wrong. Note that benchmark can run without showing any wrong behavior is because the **CurrentBPAddress** is set to null.

- Also, exceptions happen in the ``ApplyCachedDataAction`` will not be detected because the error information will not be recorded into TransactionTrace (**Does worker need to send message to router actor after it persists cache to the database?**)

- Another issue is function ``IDataProvider.PipelineSetDataAsync<T>`` should not be a generic function because there will be all kinds of the data types in the StateCache, and the generic function suggests that there will be only data with the same type in the StateCache, which is not right.

- Lack of unit test of the ``ApplyCachedDataAction``

**Comment by rosona** [comment]
WorldState module has been refactored, so close this issue.
