### ISSUE TITLE
rpc: get wrong Balance when restart the node.

### ISSUE THREAD

**Issue by hzz780** [AElfProject/AElf#457]
commit 9c6517526f5d7f3c0c3693d2f4fa7f912306a8d0

If I restart the node.  I will get the Balance when i just initialize the contract.

### demo1
1. A is the owner the contract.
2. Initialize info - (s, ELF, 25000, 10)
3. rpc: get Balance of A -> 25000.
4. A transfer 2000 to B.
5. rpc: get Balance of A & B -> 23000 2000

Then【restart the node 】

6. rpc: get Balance of A & B -> 25000 0.  But we can get the tx (A transfer 2000 to B).

### F.Y.I
we can find the the tx (A transfer 2000 to B) in the second image.

![image](https://user-images.githubusercontent.com/7567714/45407491-23686e00-b69c-11e8-8927-1b6b45a68794.png)
![image](https://user-images.githubusercontent.com/7567714/45407498-29f6e580-b69c-11e8-9dd9-95b3a2f03645.png)

**Comment by EricBlack** [comment]
Close due to issue fixed.
