### ISSUE TITLE
Need improvement for transaction signature verification

### ISSUE THREAD

**Issue by EricBlack** [AElfProject/AElf#481]
Currently ValidateTx method is almost need 20ms per time.
![image](https://user-images.githubusercontent.com/5166529/45748428-41eddc80-bc3b-11e8-96f4-cab2407314e6.png)

**Comment by gldeng** [comment]
@rosona We can replace the currently used BouncyCastle implementation with [Secp256k1.Net](https://www.nuget.org/packages/Secp256k1.Net/) (which is a wrapper for the optimized [C implementation](https://github.com/bitcoin-core/secp256k1)). According to the below test stats, the efficiency can be improved by ~20x.

Test stats:

## Signing
Repetition|Current(ms)|Secp256k1.Net(ms)
----------|-----------|---------------
1|14.319|1.361
10|13.979|0.704
100|144.31|6.609
1000|1347.958|67.738
10000|13026.812|642.685
100000|131423.906|6360.004

## Verifying
Repetition|Current(ms)|Secp256k1.Net(ms)
----------|-----------|---------------
1|22.174|0.984
10|31.931|1.169
100|254.593|10.686
1000|2512.999|100.123
10000|25417.837|1086.923
100000|256273.398|10422.293

**Comment by samfrb** [comment]
@gldeng seems like an interesting wrapper, especially that it seems that it has the recover pubkey functionality

**Comment by EricBlack** [comment]
Test on latest build, it seems not change too much.

**Comment by rosona** [comment]
Fix it 

For TxMemPool/TxHub.cs VerifySignature method perf:

# old

```
    N           Min           Max        Median           Avg        Stddev
x 33995             9           297            24     33.566201     27.280559
```

# new

```
    N           Min           Max        Median           Avg        Stddev
x 30460             0            21             0    0.25387393     1.2758351
```

**Comment by EricBlack** [comment]
Close due to fixed.
