### ISSUE TITLE
Unclean state cache

### ISSUE THREAD

**Issue by gldeng** [AElfProject/AElf#517]
## Description:
1. The state changes are [retrieved from `DataProvider`](https://github.com/AElfProject/AElf/blob/180f0ea0f88e456f26307ecf2af4b3a95f60182e/AElf.Runtime.CSharp/Executive.cs#L221)
1. The `DataProvider` [gets the changes from `StateCache`](https://github.com/AElfProject/AElf/blob/180f0ea0f88e456f26307ecf2af4b3a95f60182e/AElf.SmartContract/Contexts/DataProvider.cs#L22)
1. The `StateCache` is [all the transactions](https://github.com/AElfProject/AElf/blob/180f0ea0f88e456f26307ecf2af4b3a95f60182e/AElf.ChainController/SimpleExecutingService.cs#L84) grouped together.

In this case, the changes registered in `TransactionTrace` are not purely for that particular transaction.

The following are the reasons (not exhaustive) for registering values in `TransactionTrace`:
1. It can be used to make sure that the transactions only accessed allowed data range
1. It may be used for derive consensus on the transaction result

## Proposed Solution:
Separate the cache into two levels:
1. Data provider level, which caches only for ONE transaction
1. Data base level tied to one worker/actor (changes are flushed to permanent database after the execution of the group is finished or upon request) -- **Need careful design to ensure consistency**

**Comment by gldeng** [comment]
Epic #515

**Comment by rosona** [comment]
#540 finished

**Comment by rosona** [comment]
#540 finished

**Comment by rosona** [comment]
#540 finished
