### ISSUE TITLE
Sometimes the miner packages no transactions after generating a block

### ISSUE THREAD

**Issue by EanCuznaivy** [AElfProject/AElf#543]
The log shows this miner got several transactions to package, but after executing transactions, he broadcasted a block with 0 transaction.
This scenario is kinda hard to reproduce though.
![image](https://user-images.githubusercontent.com/17485381/47252184-e51c5680-d472-11e8-9fef-b1c1aa14d09f.png)
![image](https://user-images.githubusercontent.com/17485381/47252187-eb123780-d472-11e8-8922-d11d2971a132.png)

**Comment by EricBlack** [comment]
Fixed, not repro again.
