### ISSUE TITLE
Double block send when network is bad.

### ISSUE THREAD

**Issue by samfrb** [AElfProject/AElf#563]
When the network conditions are not good and/or the blocks get big, blocks can be sent twice. This is *sometimes* visible during a sync: when the node that's syncing requests a block and the response fails to arrive before the timeout (but the block is still in-flight), the syncing peer will re-request the block, so the node will re-receive it. 

It causes the node to enter in a re-request cycle (each block twice), eventually the node gets the block but it lags behind because of the block sizes. 

Update: after further analysis it's not so obvious why this happens, but probably a lag in the network itself. The request is send, the other node starts replying, but the first message (frame) takes 5s to get the node and even more for the rest of the block).

Proposed solution:
1. [requesting side] on request - check that the block is not in the out-queue.
2. [replying side] on timeout - check that the block is not in the in-queue.
3. [logs] log the start and end of the send. 
    [logs] log the start and end of the receive.

**Comment by samfrb** [comment]
There's been improvement on this, but after multiple refactors the issue is not reproducible.

**Comment by EricBlack** [comment]
Close due to fixed and not repro again.
