### ISSUE TITLE
Multiple nodes huge transaction execution caused nodes stopped working without any error throw

### ISSUE THREAD

**Issue by EricBlack** [AElfProject/AElf#566]
## Description
1. Run 3 BP nodes first.
2. Send huge transactions(test program parameter: 4 50) to execution.

## Result
Three nodes generate blocks normally for a while. And three nodes stopped working suddenly and no any error or exception throw.

## Screenshot
![image](https://user-images.githubusercontent.com/5166529/47629507-77f57900-db76-11e8-805b-61d8210b3128.png)

**Comment by gldeng** [comment]
Looks like some actions took too long and multiple observables were triggered. Do you have more logs?

**Comment by EricBlack** [comment]
[Multiple BPs Testing.zip](https://github.com/AElfProject/AElf/files/2524656/Multiple.BPs.Testing.zip)

**Comment by EanCuznaivy** [comment]
This is caused by last two rounds if DPoS processing information are totally same, so all BPs lost their time slot when the DPoS information generated.
Means of recovering mining automatically is under consideration.

**Comment by shiwk** [comment]
It also happens without too many txns

**Comment by EricBlack** [comment]
Fixed, and long time not repro again, close it.
