### ISSUE TITLE
Network: Until sync up to latest block, the latest block should not be announced and sent to unavailable node

### ISSUE THREAD

**Issue by EricBlack** [AElfProject/AElf#582]
## Description
When a BP node or FullNode on process to sync up block info from other BP nodes and not catch the latest block, the new generated block should not be sent to the node. Without out this category more packages sent and received from network in short time, and those latest block cannot executed and verified until all before block synced. So it's very wast of network resource on both sides especially there are too much blocks need to sync.

## Excepted strategy
1. Get the latest block height(H1) to sync up first without accept new generated block.
2. After completed first round of block sync and get latest block height again(H2), if (H2-H1) is greater than 64（or other value）, continue sync up block without accept new generated block. If (H2-H1) is smaller than 64, continue sync up block and accept the new generated block.
3. Util catch the latest height, the node should not accept the latest block to reduce network stress.

**Comment by samfrb** [comment]
Fixed with the sync refactor, see #604 
The difference with the proposed strategy is that the announcements are made but they don't trigger block requests.

**Comment by EricBlack** [comment]
Close due to fixed.
