### ISSUE TITLE
Simplify and consolidate block execution for synced block and produced block

### ISSUE THREAD

**Issue by gldeng** [AElfProject/AElf#586]
Currently block execution logics exist in both Miner and BlockExecutor.

The execution can be consolidated, in such a way that synced block can be executed as if it's a new block (same code as mining). After the block is appended to the BlockChain, it can be compared with the received block, if they have different hashes, then there is no agreement on the new block. The last executed block can be rolled back like a normal branch switch.

In this way, the rollback logic is cleaner and less prone to error and same execution code can be used for both mining and block syncing.

**Comment by EricBlack** [comment]
Done and closed.
