### ISSUE TITLE
Node should provide status check/monitor function 

### ISSUE THREAD

**Issue by EricBlack** [AElfProject/AElf#595]
## Description
Node should provide status checking/monitor function to verify current status whether is normal or not, including following aspects:
+ Status on latest height block, whether need to rollback or sync up latest block.
+ Can continue to execute block, if not stop request new block pack from network.
+ Can continue to generate new block, if not restart miner process again.

**Comment by rosona** [comment]
we already have WebAPI (chainStatus) for chain's monitor.
