### ISSUE TITLE
BlockSet: strange logs

### ISSUE THREAD

**Issue by hzz780** [AElfProject/AElf#599]
branch: dev
commit: 15551b0f7e669dad10a5f50237256efd55cf54a1

every round will get  incremental log:  'Trace - BlockSet][xx]: Removed block of height xxxx from executed block dict. '

Picture for details:

![image](https://user-images.githubusercontent.com/7567714/47995845-a6082980-e131-11e8-8830-e75540408c01.png)

**Comment by EricBlack** [comment]
Fixed
