### ISSUE TITLE
NServiceKit.Redis

### ISSUE THREAD

**Issue by lwqwag** [AElfProject/AElf#601]
1.This nuget (NServiceKit.Redis) is built  as a netframework libray  from redis database,Would you consider change a dotnetcore nuget or netstanderd nuget library?
2.When project inits, IKeyValueDatabase as a di item into the project

**Comment by rosona** [comment]
Thanks report this issue, we will fix it with #602.

**Comment by EricBlack** [comment]
Fixed.
