### ISSUE TITLE
[Demand] need a new rpc api: get_txs_result

### ISSUE THREAD

**Issue by hzz780** [AElfProject/AElf#618]
The api 'get_tx_result' is not enough. We need ''get_txs_result'.

When we need to get all transactions of a block, using this API wastes lots of resource especially network resource.

For example. We have to call the API 10 times to get 10 transactions's information.

**Comment by hzz780** [comment]
> get_txs_result_by_blockhash [blockhash] [offset=0] [num=10]

Good job.

**Comment by EricBlack** [comment]
Close due to new feature added.

**Comment by rosona** [comment]
Related PR: #663
