### ISSUE TITLE
[WIP] Voting mechanism and update miners of DPoS consensus

### ISSUE THREAD

**Issue by EanCuznaivy** [AElfProject/AElf#621]
- [x] MinersField -> OngoingMinersField. Use OngoingMiners to record multiple miners lists of different rounds.

- [x] Share the miners list from main chain to side chain because of the merged mining.

- [x] Users lock ELF token to get tickets. (Need the design of Token Contract.)

- [x] Related data structures: Candidates, Tickets, VotingRecord, ElectionSnapshot, and so on.

- [x] Methods for BP: AnnounceElection, QuitElection.

- [x] Methods for voter: GetTickets, Vote, Regret, Withdraw.

- [x] Basically use DPoS transaction `UpdateAElfDPoS` to update the miners list automatically.

- [x] The EBP of proper round have the priority to publish a `InitializeAElfDPoS` transaction to adapt the mining process with new miners list.

- [x] Other BP also has a chance to publish `InitializeAElfDPoS` transaction if that EBP failed to do so.

- [ ] All the tests.

Related branch: feature-vote

**Comment by rosona** [comment]
related issue: #598
