### ISSUE TITLE
[Demand] rpc api: need use String to transfer BigInt

### ISSUE THREAD

**Issue by hzz780** [AElfProject/AElf#665]
In javascript，Number.MAX_SAFE_INTEGER = 2^53 - 1;
We will lose something when we JSON.parse(Object), if there is a BigInt in Object.
We need use String to transfer BigInt.

For Example:
18446744073709551615

Error:
'{"BigInt":18446744073709551615}'
JSON.parse -> { BigInt: 18446744073709552000' }

Right:
'{"BigInt":"18446744073709551615"}'
JSON.parse -> { BigInt:"18446744073709551615"}
BigInt("18446744073709551615")  -> 18446744073709551615n

**Comment by loning** [comment]
implement a webapi parameters decimal/bigint serializer

**Comment by loning** [comment]
I mean implement in C#

**Comment by hzz780** [comment]
(☆▽☆)

**Comment by hzz780** [comment]
protobuf.js -> use long.js to deal bigint
