### ISSUE TITLE
[Proposal] Proposal expired issue 

### ISSUE THREAD

**Issue by EricBlack** [AElfProject/AElf#701]
## Description
1. Proposal status is expired, but status is still not changed.
```
ubuntu@aelf-test-1:/home/aelf/github/AElf/AElf.CLI2/bin/Debug/netcoreapp2.1$ CLI2 check-proposal bbd81eec959de119d4ff02332baff4f620da8fb31ffee27aff1fe319cd83ecd0 $ENV
checking ..
got it!
{
  "result": {
    "proposal_name": "Testing proposal name",
    "multi_sig": "ELF_5SLtAu2PfYg7fBzgTHsi3GuX3uuJZiGeiQqQvDrnhhiu5kd",
    "expired_time": "2018-12-14T09:36:04.992Z",
    "TxnData": "0a200a1ec444ffa0e193b71b742a8ab4a41ecb22a773e4c6f2be6e6f695d423fcfd612200a1e96d8bf2dccf2ad419d02ed4a7b7a9d77df10617c4d731e766ce8dde63535320a496e697469616c697a653a0a0a015b12016e180020005003",
    "status": "ToBeDecided",
    "proposer": "ELF_UxLur8StUYHTqTtRCGRnpcQSCgPUqxoe3DUQsgAYUM9Tyj"
  }
}
```

2. Proposal expired should not allow to continue approve
ubuntu@aelf-test-1:/home/aelf/github/AElf/AElf.CLI2/bin/Debug/netcoreapp2.1$ CLI2 approve-proposal 1890363a590241eae806367ea98c8dc65f6f71366f48222662f004cbe6f736ff $ENV
Unlocking account ...
tx_hash is: 9a186dfc5c9087d6af989d37adabfac4aa52dbf3ad70eac1e73ab7d031226d17                 TxStatus is:  Mined                                                                          
Success.

**Comment by shiwk** [comment]
@EricBlack Proposal expired bug has been fixed.

**Comment by EricBlack** [comment]
Issue 1 would not be fixed due to by design.
Issue 2 closed due to fixed.
