### ISSUE TITLE
Simplify Configuration

### ISSUE THREAD

**Issue by gldeng** [AElfProject/AElf#721]
Currently we have too many json config files which is very unfriendly to user (We don't remember which files we need to change. And we don't remember which files are necessary and which are not.)

Can we simplify the configuration using the standard [Configuration Framework](https://github.com/aspnet/Extensions/tree/master/src/Configuration)?

I would prefer put all json configuration into one file and current config separated by file can be put into sections.

**Comment by rosona** [comment]
related issues #824 #800
