### ISSUE TITLE
services and managers refactor

### ISSUE THREAD

**Issue by loning** [AElfProject/AElf#754]
manager: should be stateless
context: create the new type to store ChainId and currentBlockHash, or currentHeight.
service: should be stateless, but can inject a context from the constructor, and we should make sure the context cannot be changed. so maybe we need to do a clone when the context was injected.

```
interface IMyContext{
Hash ChainId {get;}
long CurrentHeight{get;}
Hash CurrentBlockHash{get;}
}

class OneService{
//inject it from constructor, and should be a clone from the container
private IMyContext _context;

public Task MethodOneAsync(Transaction tx){
var chainId=_context.ChainId;
//....
}
}

```

It may work like AbpSession 

https://aspnetboilerplate.com/Pages/Documents/Abp-Session

**Comment by loning** [comment]
@gldeng @rosona  needs your ideas:)

**Comment by gldeng** [comment]
I agree we can follow the Domain Drive Design and can use ABP as a reference. Besides manager and service, I think we need to sort out all entities/types/services.

Some thoughts on these concepts:
Entity: mapped to domain concept
Manager: handles multiple entities of the same type
Service: performs some activities that require collaboration of multiple types of entities

**Comment by shiwk** [comment]
> manager: should be stateless
> context: create the new type to store ChainId and currentBlockHash, or currentHeight.
> service: should be stateless, but can inject a context from the constructor, and we should make sure the context cannot be changed. so maybe we need to do a clone when the context was injected.
> 
> ```
> interface IMyContext{
> Hash ChainId {get;}
> long CurrentHeight{get;}
> Hash CurrentBlockHash{get;}
> }
> 
> class OneService{
> //inject it from constructor, and should be a clone from the container
> private IMyContext _context;
> 
> public Task MethodOneAsync(Transaction tx){
> var chainId=_context.ChainId;
> //....
> }
> }
> ```
> It may work like AbpSession
> 
> https://aspnetboilerplate.com/Pages/Documents/Abp-Session

@loning I like this as maintained session can optimize DB access especially in many cases for the same target data. And for me what is better is whether we can reduce storage types with this session improvement. There are more than 15 specific storage types in current implementation :-D.
