### ISSUE TITLE
Zero fee contract methods need more security check and avoid DDos attack

### ISSUE THREAD

**Issue by EricBlack** [AElfProject/AElf#783]
## Description
Our node exist lot of contract method execution fee is zero like DPos contract, and also sidechain index write on main node also will execution with free. 
And currently implement about this is just by tag filter '[Fee(0)]', this is not safe, following bad situation will be       happened:
- [ ] User can call those free contracts methods without limitation.
- [x] Contracts developer also can set this tag.

**Comment by gldeng** [comment]
@EricBlack Developer shouldn't set fee to 0 unless it's a system transaction. System transaction won't be allowed from regular user, only BP can send such transactions.
An item can be added in #727 to disallow deployment of contract with 0 fees.
