### ISSUE TITLE
Standalone node stop normally and restart not works

### ISSUE THREAD

**Issue by EricBlack** [AElfProject/AElf#785]
## Description
Stop standalone node normally(Ctrl-C or kill without parameter '-9') and restart node again, node cannot recover to work normally. And no any error or exception thrown.
PS: Multiple nodes restart works normally.
1. Stop node
![image](https://user-images.githubusercontent.com/5166529/50766380-f1ff5800-12b3-11e9-9d01-c19f536c5670.png)
2. Restart node
![image](https://user-images.githubusercontent.com/5166529/50766389-f9befc80-12b3-11e9-8f77-373a84ec214c.png)

**Comment by EanCuznaivy** [comment]
Fixed this issue in #780

**Comment by EricBlack** [comment]
Fixed and verified on feature-vote branch
