### ISSUE TITLE
Execute block - Incorrect merkle trees

### ISSUE THREAD

**Issue by EricBlack** [AElfProject/AElf#820]
## Description
We got some scenario can be caused block execution failed by Incorrect merkle trees. For details please refer attached logs:
-  All nodes are forked, and then one of nodes got Incorrect merkle tree. 
[All nodes forked.zip](https://github.com/AElfProject/AElf/files/2763698/All.nodes.forked.zip)
- On of node rollback successful, but then continue to execute later block got incorrect merkle tree.
[Incorrect MerkleTree.zip](https://github.com/AElfProject/AElf/files/2763703/Incorrect.MerkleTree.zip)
- Run lot of vote operation(100 txs), and then node would be timeout first, then would be got Incorrect merkle tree.
[Vote-IncorrectMerkleTree.zip](https://github.com/AElfProject/AElf/files/2763723/Vote-IncorrectMerkleTree.zip)

**Comment by rosona** [comment]
out of date.
