### ISSUE TITLE
Chain ID => Int32

### ISSUE THREAD

**Issue by loning** [AElfProject/AElf#822]
Now we use Hash to store a chain ID, but chain id is not a hash

- [x] store chain id as int32 in state manager and chain manager
- [ ] remove hash <> int32 implicit operator

**Comment by loning** [comment]
@shiwk after your reorganize of cross chain, we need to totally remove hash style of chain id

**Comment by shiwk** [comment]
> @shiwk after your reorganize of cross chain, we need to totally remove hash style of chain id

@loning Yes, in process.

**Comment by loning** [comment]
already fixed
