### ISSUE TITLE
Two proposals return the same release transaction id

### ISSUE THREAD

**Issue by YueZh127** [AElfProject/AElf#829]
Create two proposals that have the same method and the same params, after releasing these proposals, the release transaction id is same.

**Comment by YueZh127** [comment]
after CLI SDK improved , still have this issue

**Comment by shiwk** [comment]
> after CLI SDK improved , still have this issue

Nuget package update needed.

**Comment by YueZh127** [comment]
The proposals changed and retest on the new version
