### ISSUE TITLE
Code refactor cause some projects namespace chaos 

### ISSUE THREAD

**Issue by EricBlack** [AElfProject/AElf#876]
## Description
During code refactor, some times we just copied code from one project to another project but did not modify namespace name. Maybe we still need more projects reference after refactor completed.
Eg1:
![image](https://user-images.githubusercontent.com/5166529/52842721-f03e7500-313a-11e9-9531-6e0093afb72d.png)
Eg2:
![image](https://user-images.githubusercontent.com/5166529/52842788-24b23100-313b-11e9-87f5-a1386c32e961.png)

**Comment by rosona** [comment]
Fixed as:
AElf.Kernel.Types namespace is AElf.Kernel
The AElf.Types namespce change to AElf
